elucidsoft/dotnet-stellar-sdk

stellar-dotnet-sdk/xdr/XdrDataInputStream.cs
This change is to fix when the transaction is being decoded and there is a memo present but the tail variable is 0 when the ReadFixOpaque is run - the position is not moved forward on the stream in these cases. -
- [x ] Bug fix (non-breaking change which fixes an issue)
=> change to fix transaction decode when NO tail and memo present

stellar-dotnet-sdk-test/xdr/XdrDataStreamTest.cs, stellar-dotnet-sdk/xdr/XdrDataInputStream.cs
When decoding DataValue, XdrDataInputStream would move _pos forward
both ReadFixOpaque and Read, resulting in and IndexOutOfRange exception
when decoding data with padding.
I noticed the bug trying to decode (with `Transaction.FromEnvelopeXdr`) this transaction
```
AAAAAPOyEZDfMVqKSzP4Gw9Syuyw/6jd98fCtQ0t2rHCpg0IAAAAZACn6pgAAAABAAAAAAAAAAAAAAABAAAAAAAAAAoAAAADS0VZAAAAAAEAAAAFVkFMVUUAAAAAAAAAAAAAAA==
```
Set a breakpoint in `xdr.ManageDataOp:Decode` and notice how it reads too many bytes, resulting in a exception when decoding `TransactionExt`.
This is my fix, but I'm not too familiar with the Xdr decoder so I hope I didn't mess anything up!
=> Fix double increment of _pos when decoding DataValue

stellar-dotnet-sdk-test/OperationTest.cs, stellar-dotnet-sdk/AccountMergeOperation.cs, stellar-dotnet-sdk/AllowTrustOperation.cs, stellar-dotnet-sdk/BumpSequenceOperation.cs, stellar-dotnet-sdk/Operation.cs, stellar-dotnet-sdk/OperationThreshold.cs, stellar-dotnet-sdk/SetOptionsOperation.cs
I have added a `Threshold` property to operations with values `Low | Medium | High`. In most projects I end up writing extension methods that do this, so I thought it could be an useful addition to the library.
Knowing the threshold level of an operation (and in turn of a transaction) is useful when validating the transaction *before* sending to the network. For example, if you have a multi-sig account that requires a second signature for high threshold operations, the wallet could display an helpful message to the user before submitting the transaction.
=> Add Threshold property to Operation

stellar-dotnet-sdk-console/Program.cs, stellar-dotnet-sdk-test/TransactionTest.cs, stellar-dotnet-sdk-test/requests/AccountsRequestBuilderTest.cs, stellar-dotnet-sdk-test/requests/FriendBotRequestBuilderTest.cs, stellar-dotnet-sdk-test/requests/TradesRequestBuilderTest.cs, stellar-dotnet-sdk/requests/AccountsRequestBuilder.cs, stellar-dotnet-sdk/requests/FriendBotRequestBuilder.cs, stellar-dotnet-sdk/requests/TradesRequestBuilder.cs, stellar-dotnet-sdk/responses/AccountResponse.cs
I think this fixes #157 (I had the same issue). I also finished converting requests to use `string` instead of `KeyPair`.
=> Fix AccountResponse and requests

appveyor.yml, stellar-dotnet-sdk-xdr/stellar-dotnet-sdk-xdr.csproj, stellar-dotnet-sdk/stellar-dotnet-sdk.csproj
At the moment `stellar-dotnet-sdk-xdr` is a nuget dependency of `stellar-dotnet-sdk` but it's not published on nuget. This fixes it.
=> Publish stellar-dotnet-sdk-xdr to Nuget

stellar-dotnet-sdk-console/Program.cs, stellar-dotnet-sdk/EventSource.cs, stellar-dotnet-sdk/EventSourceState.cs, stellar-dotnet-sdk/ServerSentErrorEventArgs.cs, stellar-dotnet-sdk/ServerSentEventArgs.cs, stellar-dotnet-sdk/StateChangeEventArgs.cs
Streams were throwing an exception on byebye. It seems there was a behavior somewhere that caused this to occur.  Now if a Stream connection recieves a byebye the SDK will wait 1 second, then Reconnect and resume the stream were it left off based on the internally stored Cursor position.
=> Fix for Stream Disconnecting on byebye

stellar-dotnet-sdk/Network.cs, stellar-dotnet-sdk/requests/FriendBotRequestBuilder.cs
This is a small change that exposes the public and testnet passphrases to users. It was mentioned in #109
=> Make NetworkPassphrase constants public

stellar-dotnet-sdk/stellar-dotnet-sdk.csproj
This fixes a problem in the SSE streaming client where the
`Last-Event-Id` header was not sent to Horizon.
=> Update LaunchDarkly.EventSource package

stellar-dotnet-sdk-test/WebAuthenticationTest.cs, stellar-dotnet-sdk/TimeBounds.cs, stellar-dotnet-sdk/WebAuthentication.cs
=> Sep 10 update

stellar-dotnet-sdk-test/TimeBoundsTest.cs, stellar-dotnet-sdk/TimeBounds.cs, stellar-dotnet-sdk/WebAuthentication.cs
I added two overloads to the `TimeBounds` ctor so that it's easier to build timebounds that are valid from e.g. now.
=> Add TimeSpan overloads to TimeBounds ctor

stellar-dotnet-sdk-test/AccountTest.cs, stellar-dotnet-sdk-test/TransactionTest.cs, stellar-dotnet-sdk/Account.cs, stellar-dotnet-sdk/ITransactionBuilderAccount.cs, stellar-dotnet-sdk/TransactionBase.cs, stellar-dotnet-sdk/TransactionBuilder.cs, stellar-dotnet-sdk/responses/AccountResponse.cs
This PR also includes 9891652693feeb1013c8e63c67f0ad785708ae03, 7321d7abf8818761b9b28038f945e862f900cfb2 and 97ba78e2e02a0fcc94862d3c4746d7c655a3da63. 
Similarly to the js sdk, I added a `TransactionBase` class for `Transaction` and `FeeBumpTransaction`. I renamed the `Transaction.Builder` to `TransactionBuilder` but kept the inner class with a deprecation warning for backward compatibility.
`Account` did not play well with the new `MuxedAccount`, so I added an overload of the ctor to accept `MuxedAccount`. If the user passes a string to the ctor, we assume it's a normal keypair and parse it with `KeyPair.FromAccountId`. That way we are backward compatible with old code.
=> fix building transaction with muxed account source

stellar-dotnet-sdk-test/ServerCheckMemoRequiredTest.cs, stellar-dotnet-sdk/IAccountId.cs, stellar-dotnet-sdk/InflationOperation.cs, stellar-dotnet-sdk/KeyPair.cs, stellar-dotnet-sdk/MuxedAccountMed25519.cs, stellar-dotnet-sdk/PathPaymentStrictReceiveOperation.cs, stellar-dotnet-sdk/PathPaymentStrictSendOperation.cs, stellar-dotnet-sdk/PaymentOperation.cs, stellar-dotnet-sdk/Server.cs
If the destination of a payment is a muxed account we do not need to check for the memo.
=> Fix memo check to support muxed accounts

stellar-dotnet-sdk-test/WebAuthenticationTest.cs, stellar-dotnet-sdk/WebAuthentication.cs
Added homeDomain check in WebAuthentication.cs
=> SEP-10 3.0

stellar-dotnet-sdk-test/ClaimPredicateTest.cs, stellar-dotnet-sdk-test/responses/OperationDeserializerTest.cs, stellar-dotnet-sdk-test/stellar-dotnet-sdk-test.csproj, stellar-dotnet-sdk-test/testdata/operations/operationClaimableBalanceAbsBeforeMaxInt.json, stellar-dotnet-sdk/ClaimPredicate.cs, stellar-dotnet-sdk/ClaimPredicateBeforeAbsoluteTime.cs, stellar-dotnet-sdk/responses/Predicate.cs
This is the fix for #284 that we discussed. Since there is no way to represent an Iso8601 date in .NET, we simply don't parse the long/string values.
=> fix: don't parse claim predicate datetime

stellar-dotnet-sdk-test/OperationTest.cs, stellar-dotnet-sdk/ClaimClaimableBalanceOperation.cs
Fixes #293 with:
* Adds support for full 36 bytes of balance id (4 bytes type followed by 32 bytes for the body)
* Keeps support of 32 bytes to keep it as a non-breaking change
* Allows for balance id to be passed in as a string
The tests I've added match the expected behaviour of the tests from the Java SDK which cover the same functionality: https://github.com/stellar/java-stellar-sdk/blob/32331b3a5a4cf62eb6820b5e975032b9ab13887c/src/test/java/org/stellar/sdk/OperationTest.java#L757
=> Support passing in a string for balance id

stellar-dotnet-sdk-test/ServerTest.cs, stellar-dotnet-sdk/Server.cs, stellar-dotnet-sdk/SubmitTransactionOptions.cs
Fixes #296 
- Added `EnsureSuccess` to `SubmitTransactionOptions`
If set to `true`, response of `POST /transactions` will be checked if its status code is success or not
=> Check for success while calling SubmitTransaction

.config/dotnet-tools.json, .editorconfig, appveyor.yml
This PR adds an extra step to the CI to check that all files are formatted accordingly with `.editorconfig`.
I had to update the Visual Studio image to something more modern to make the tool work.
=> Check file formatting during build

stellar-dotnet-sdk-test/ClaimPredicateTest.cs, stellar-dotnet-sdk-test/KeyPairTest.cs, stellar-dotnet-sdk/KeyPair.cs
This is a fix to #309, note that I implemented `IEquatable<T>` because I think it makes more sense than implementing `IComparable<T>`.
=> Equatable KeyPair

stellar-dotnet-sdk-test/AccountFlagTest.cs, stellar-dotnet-sdk-test/ServerCheckMemoRequiredTest.cs, stellar-dotnet-sdk-test/responses/AccountDeserializerTest.cs, stellar-dotnet-sdk-test/stellar-dotnet-sdk-test.csproj, stellar-dotnet-sdk-test/testdata/account.json, stellar-dotnet-sdk/AccountFlag.cs, stellar-dotnet-sdk/responses/Balance.cs, stellar-dotnet-sdk/responses/Flags.cs
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [   ] New feature (non-breaking change which adds functionality)
- [   ] Breaking change (fix or feature that would cause existing functionality to change)
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] My code follows the code style of this project.
- [   ] My change requires a change to the documentation.
- [   ] I have updated the documentation accordingly.
- [ x ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.
=> Fix liquidity pool balance deserialization.

stellar-dotnet-sdk-test/responses/AssetPageDeserializerTest.cs, stellar-dotnet-sdk-test/testdata/assetPage.json, stellar-dotnet-sdk/responses/AssetResponse.cs
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] My code follows the code style of this project.
- [ x ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.
=> AssetResponse - Added num_liquidity_pools and liquidity_pools_amount

stellar-dotnet-sdk-test/requests/AccountsRequestBuilderTest.cs, stellar-dotnet-sdk/requests/RequestBuilder.cs
We are having issues using a Node API provider that requires a path prefix like (`https://provider.com/rpc/xlm/{auth-key}/`).
Currently the SDK only uses the domain part of the supplied Horizon URI, and the path is fully replaced by the segments generated by the various RequestBuilders.
Through this change the original path is now stored and used later on when adding the segments again.
I'm not entirely sure in what category this falls (bug/ feature/ breaking).
If users have set-up the serverUri with a path that shouldn't be there, it would be included now.
I'm happy to update the version once it's clear if it's major/minor/fix.
As a temporary workaround we're using the following:
```fsharp
let prefixUriBuilderOfSnd (first: string) (second: Uri) =
let urlBuilder = new UriBuilder(first) …
```
=> Support ServerUri with a path included

appveyor.yml, stellar-dotnet-sdk/WebAuthentication.cs
- [x ] All new and existing tests passed.
=> Add GracePeriod

stellar-dotnet-sdk-test/operations/FeeBumpOperationTest.cs, stellar-dotnet-sdk/TransactionBuilder.cs, stellar-dotnet-sdk/responses/FeeBumpTransactionResultFailed.cs, stellar-dotnet-sdk/responses/FeeBumpTransactionResultSuccess.cs, stellar-dotnet-sdk/responses/InnerTransactionResultPair.cs, stellar-dotnet-sdk/responses/TransactionResult.cs, stellar-dotnet-sdk/responses/TransactionResultSuccess.cs
Fix for [issue 388](https://github.com/elucidsoft/dotnet-stellar-sdk/issues/388).
Also fixed the fee bump fee according to the Stellar documentation.
https://developers.stellar.org/docs/encyclopedia/fee-bump-transactions#fee
It states that the fee set on the fee bump transaction should be the amount of stopen that you would like to pay for executing only the fee bump operation which is 1 operation. So this should be independent from the inner transaction.
=> Fix for missing fee bump result (issue 388)
