elucidsoft/dotnet-stellar-sdk

- TestConsole/Program.cs
- stellar-dotnetcore-sdk/EventSource.cs
- stellar-dotnetcore-sdk/MemoText.cs
- stellar-dotnetcore-sdk/Server.cs
- stellar-dotnetcore-sdk/TooManySignaturesException.cs
- stellar-dotnetcore-sdk/Transaction.cs
- stellar-dotnetcore-sdk/requests/OperationsRequestBuilder.cs
Added to the  OperationRequestBuilder.cs file for streaming operations, slightly modified EventSource for streaming in general.
Added some extra stuff for creating unsigned envelopes that may or may not belong(for being able to build a transaction and store or send elsewhere but sign later), as well as an overload for being able to submit transactions directly from base64
> Added OperationRequestBuilder.cs and modified EventSource.cs

- stellar-dotnetcore-sdk/Asset.cs
- stellar-dotnetcore-sdk/Server.cs
- stellar-dotnetcore-sdk/requests/AccountsRequestBuilder.cs
- stellar-dotnetcore-sdk/requests/AssetsRequestBuilder.cs
- stellar-dotnetcore-sdk/requests/EffectsRequestBuilder.cs
- stellar-dotnetcore-sdk/requests/LedgersRequestBuilder.cs
- stellar-dotnetcore-sdk/requests/OffersRequestBuilder.cs
- stellar-dotnetcore-sdk/requests/OperationsRequestBuilder.cs
- stellar-dotnetcore-sdk/requests/PaymentsRequestBuilder.cs
- stellar-dotnetcore-sdk/requests/TransactionsRequestBuilder.cs
- stellar-dotnetcore-sdk/responses/AssetResponse.cs
- stellar-dotnetcore-sdk/responses/JsonSingleton.cs
- stellar-dotnetcore-unittest/requests/AssetsRequestBuilderTest.cs
- stellar-dotnetcore-unittest/requests/OperationsRequestBuilderTest.cs
- stellar-dotnetcore-unittest/responses/AssetPageDeserializerTest.cs
- stellar-dotnetcore-unittest/responses/testdata/assetPage.json
- stellar-dotnetcore-unittest/stellar-dotnetcore-unittest.csproj
> All assets endpoint

- stellar-dotnetcore-sdk/Server.cs
- stellar-dotnetcore-sdk/requests/TradesAggregationRequestBuilder.cs
- stellar-dotnetcore-sdk/requests/TradesRequestBuilder.cs
- stellar-dotnetcore-sdk/responses/JsonSingleton.cs
- stellar-dotnetcore-sdk/responses/LedgerResponse.cs
- stellar-dotnetcore-sdk/responses/TradeAggregationResponse.cs
- stellar-dotnetcore-sdk/responses/TradeResponse.cs
- stellar-dotnetcore-sdk/responses/operations/OperationResponse.cs
- stellar-dotnetcore-unittest/requests/TradeAggregationsRequestBuilderTest.cs
- stellar-dotnetcore-unittest/requests/TradesRequestBuilderTest.cs
- stellar-dotnetcore-unittest/responses/TradeAggregationsPageDeserializerTest.cs
- stellar-dotnetcore-unittest/responses/TradesPageDeserializerTest.cs
- stellar-dotnetcore-unittest/responses/testdata/tradeAggregationsPage.json
- stellar-dotnetcore-unittest/responses/testdata/tradesPage.json
- stellar-dotnetcore-unittest/stellar-dotnetcore-unittest.csproj
-Updates trade enpoint reponse and request.
-Updates operation response.
-Updates ledger response
-Updates unit tests.
-Added unit test for TradeAggregationsRequestBuilderTest.
> Added TradeAggregations Endpoint

- stellar-dotnetcore-sdk/StrKey.cs
- stellar-dotnetcore-unittest/StrKeyTest.cs
Hi, I added a couple of methods to StrKey. Ported from the Stellar JS SDK.
> Added boolean Ed25519 validation methods with tests

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- CONTRIBUTING.md
- PULL_REQUEST_TEMPLATE.md
- stellar-dotnetcore-sdk/StrKey.cs
- stellar-dotnetcore-sdk/responses/AccountResponse.cs
- stellar-dotnetcore-unittest/StrKeyTest.cs
- stellar-dotnetcore-unittest/responses/AccountDeserializerTest.cs
- stellar-dotnetcore-unittest/responses/testdata/account.json
> Merge latest master changes into dotnetstandard-2.0

- stellar-dotnet-sdk-test/responses/OperationDeserializerTest.cs
- stellar-dotnet-sdk-test/responses/testdata/operationPathPayment.json
- stellar-dotnet-sdk/responses/operations/PathPaymentOperationResponse.cs
> Fix for #17

- stellar-dotnet-sdk-test/requests/ClientProtocolExceptionTest.cs
- stellar-dotnet-sdk-test/requests/HttpResponseExceptionTest.cs
- stellar-dotnet-sdk-test/requests/TooManyRequestsExceptionTest.cs
> Some very basic code coverage improvements

- docfx/.gitignore
- docfx/Generate.sh
- docfx/templates/docfx-tmpl/LICENSE.md
- docfx/templates/docfx-tmpl/src/partials/affix.tmpl.partial
- docfx/templates/docfx-tmpl/src/partials/class.header.tmpl.partial
- docfx/templates/docfx-tmpl/src/partials/class.tmpl.partial
- docfx/templates/docfx-tmpl/src/partials/enum.tmpl.partial
- docfx/templates/docfx-tmpl/src/partials/namespace.tmpl.partial
- docfx/templates/docfx-tmpl/src/styles/main.css
- docfx/templates/docfx-tmpl/src/styles/main.js
Added missing template folder
Automatic generation and upload via Generate.sh
Modified .gitignore of docfx
> Docs Fix 2

- stellar-dotnet-sdk-test/TransactionTest.cs
- stellar-dotnet-sdk/Transaction.cs
Fixed converting a transaction to a unsigned xdr object by adding an empty array.
> Fixed null reference when converting a Transaction to an unsigned XDR

- stellar-dotnet-sdk-test/TransactionTest.cs
- stellar-dotnet-sdk/Memo.cs
- stellar-dotnet-sdk/MemoHashAbstract.cs
- stellar-dotnet-sdk/MemoId.cs
- stellar-dotnet-sdk/MemoNone.cs
- stellar-dotnet-sdk/MemoText.cs
- stellar-dotnet-sdk/TimeBounds.cs
- stellar-dotnet-sdk/Transaction.cs
Based on https://github.com/stellar/java-stellar-sdk/pull/114
> Deserialize XDR to Transaction

- stellar-dotnet-sdk/requests/AccountsRequestBuilder.cs
- stellar-dotnet-sdk/requests/EffectsRequestBuilder.cs
- stellar-dotnet-sdk/requests/LedgersRequestBuilder.cs
- stellar-dotnet-sdk/requests/OperationsRequestBuilder.cs
- stellar-dotnet-sdk/requests/PaymentsRequestBuilder.cs
- stellar-dotnet-sdk/requests/RequestBuilder.cs
- stellar-dotnet-sdk/requests/TransactionsRequestBuilder.cs
Refactor the Stream Method on RequestBuilders for code re-use.
> Refactor Stream Method

- stellar-dotnet-sdk/requests/AccountsRequestBuilder.cs
- stellar-dotnet-sdk/requests/AssetsRequestBuilder.cs
- stellar-dotnet-sdk/requests/EffectsRequestBuilder.cs
- stellar-dotnet-sdk/requests/FriendBotRequestBuilder.cs
- stellar-dotnet-sdk/requests/LedgersRequestBuilder.cs
- stellar-dotnet-sdk/requests/OffersRequestBuilder.cs
- stellar-dotnet-sdk/requests/OperationsRequestBuilder.cs
- stellar-dotnet-sdk/requests/OrderBookRequestBuilder.cs
- stellar-dotnet-sdk/requests/PathsRequestBuilder.cs
- stellar-dotnet-sdk/requests/PaymentsRequestBuilder.cs
- stellar-dotnet-sdk/requests/RequestBuilder.cs
- stellar-dotnet-sdk/requests/TradesAggregationRequestBuilder.cs
- stellar-dotnet-sdk/requests/TradesRequestBuilder.cs
- stellar-dotnet-sdk/requests/TransactionsRequestBuilder.cs
> Now the RequestBuilders will implement 3 possible RequestBuilder classes

- stellar-dotnet-sdk-test/MemoTest.cs
- stellar-dotnet-sdk/MemoReturnHash.cs
> Fix MemoReturnHash.ToXdr not working correctly.

- .travis.yml
- dotnetcore/stellar-dotnetcore-sdk.csproj
- stellar-dotnet-sdk-console/stellar-dotnet-sdk-console.csproj
- stellar-dotnet-sdk-test/stellar-dotnet-sdk-test.csproj
Upgraded .NET Core to 2.1, unit tests still pass and everything is still working.
Addresses issue #41
> Upgraded .NET Core version to 2.1

- stellar-dotnet-sdk/Account.cs
- stellar-dotnet-sdk/AccountFlag.cs
- stellar-dotnet-sdk/Asset.cs
- stellar-dotnet-sdk/federation/Federation.cs
Need to update the docs for this change.
> Some fixes for how the documentation in the code looks when generated.

- README.md
- stellar-dotnet-sdk-test/OperationTest.cs
- stellar-dotnet-sdk-test/responses/EffectDeserializerTest.cs
- stellar-dotnet-sdk-test/responses/OperationDeserializerTest.cs
- stellar-dotnet-sdk-test/stellar-dotnet-sdk-test.csproj
- stellar-dotnet-sdk-test/testdata/effectOfferCreated.json
- stellar-dotnet-sdk-test/testdata/effectOfferRemoved.json
- stellar-dotnet-sdk-test/testdata/effectOfferUpdated.json
- stellar-dotnet-sdk-test/testdata/effectUnknown.json
- stellar-dotnet-sdk-test/testdata/operationBumpSequence.json
- stellar-dotnet-sdk-test/testdata/operationUnknown.json
- stellar-dotnet-sdk-test/testdata/sequenceBumped.json
- stellar-dotnet-sdk/BumpSequenceOperation.cs
- stellar-dotnet-sdk/Operation.cs
- stellar-dotnet-sdk/responses/EffectDeserializer.cs
- stellar-dotnet-sdk/responses/OperationDeserializer.cs
- stellar-dotnet-sdk/responses/effects/SequenceBumpedEffectResponse.cs
- stellar-dotnet-sdk/responses/operations/BumpSequenceOperationResponse.cs
> Bump sequence

- README.md
> Added CodeFactor Badge

- stellar-dotnet-sdk/Util.cs
- stellar-dotnet-sdk/responses/operations/ManageOfferOperationResponse.cs
> Last couple issues

- stellar-dotnet-sdk-test/TransactionTest.cs
- stellar-dotnet-sdk/responses/TransactionDeserializer.cs
> fix extra line

- stellar-dotnet-sdk-test/responses/AccountDeserializerTest.cs
- stellar-dotnet-sdk-test/responses/OperationDeserializerTest.cs
- stellar-dotnet-sdk-test/stellar-dotnet-sdk-test.csproj
- stellar-dotnet-sdk-test/testdata/account.json
- stellar-dotnet-sdk-test/testdata/operationSetOptionsNonEd25519Key.json
- stellar-dotnet-sdk/responses/Signer.cs
- stellar-dotnet-sdk/responses/operations/SetOptionsOperationResponse.cs
> Added support for NonEd25519 keys

- stellar-dotnet-sdk-test/TransactionTest.cs
- stellar-dotnet-sdk/Network.cs
- stellar-dotnet-sdk/Transaction.cs
This is the feature we discussed in #104. I made sure the class has the same behaviour as before for `Sign`/`Hash`/`SignatureBase`.
> Sign transactions for networks different than current

- stellar-dotnet-sdk-console/Program.cs
- stellar-dotnet-sdk-test/requests/AccountsRequestBuilderTest.cs
- stellar-dotnet-sdk-test/stellar-dotnet-sdk-test.csproj
- stellar-dotnet-sdk-test/testdata/accountData.json
- stellar-dotnet-sdk/requests/AccountsRequestBuilder.cs
- stellar-dotnet-sdk/responses/AccountDataResponse.cs
> Added AccountData endpoint support.

- stellar-dotnet-sdk-test/OperationTest.cs
- stellar-dotnet-sdk/InflationOperation.cs
- stellar-dotnet-sdk/Operation.cs
I noticed it was not possible to create and parse operations of type inflation. This PR fixes that.
> Add InflationOperation class

- stellar-dotnet-sdk-test/AccountTest.cs
- stellar-dotnet-sdk/Account.cs
- stellar-dotnet-sdk/ITransactionBuilderAccount.cs
- stellar-dotnet-sdk/Transaction.cs
- stellar-dotnet-sdk/responses/AccountResponse.cs
Fix for issue #118
- [yes] Bug fix (non-breaking change which fixes an issue)
- [no] New feature (non-breaking change which adds functionality)
- [yes] Breaking change (fix or feature that would cause existing functionality to change)
- [yes] I have read the **CONTRIBUTING** document.
- [yes] My code follows the code style of this project.
- [yes] My change requires a change to the documentation.
- [no] I have updated the documentation accordingly.
- [no] I have added tests to cover my changes.
- [yes] All new and existing tests passed.
> Fix for #118

- stellar-dotnet-sdk-console/Program.cs
- stellar-dotnet-sdk/EventSource.cs
- stellar-dotnet-sdk/IEventSource.cs
- stellar-dotnet-sdk/requests/RequestBuilderStreamable.cs
> Fix for issue #123

- .gitignore
- appveyor.yml
- stellar-dotnet-sdk-test/stellar-dotnet-sdk-test.csproj
Got Appveyor CI Build server working, first step to getting the documentation to automatically generate.
> Appveyor Support

- stellar-dotnet-sdk-test/ServerTest.cs
- stellar-dotnet-sdk/Server.cs
Fix #152
(Sorry for the line end change as well)
> Identity client version and name in headers

- stellar-dotnet-sdk-test/TransactionTest.cs
- stellar-dotnet-sdk/Transaction.cs
> Allow custom base fee for transaction

- stellar-dotnet-sdk-test/responses/LedgerDeserializeTest.cs
- stellar-dotnet-sdk-test/stellar-dotnet-sdk-test.csproj
- stellar-dotnet-sdk-test/testdata/ledgerNullFailedTransactionCount.json
- stellar-dotnet-sdk/responses/LedgerResponse.cs
> Make LedgerResponse FailedTransactionCount nullable

- stellar-dotnet-sdk-test/responses/OperationDeserializerTest.cs
- stellar-dotnet-sdk-test/stellar-dotnet-sdk-test.csproj
- stellar-dotnet-sdk-test/testdata/operationManageBuyOffer.json
- stellar-dotnet-sdk-test/testdata/operationManageOffer.json
- stellar-dotnet-sdk/responses/OperationDeserializer.cs
- stellar-dotnet-sdk/responses/operations/ManageBuyOfferOperationResponse.cs
- stellar-dotnet-sdk/responses/operations/ManageOfferOperationResponse.cs
- stellar-dotnet-sdk/responses/operations/ManageSellOfferOperationResponse.cs
> Deserialize ManageBuyOffer operation response

- stellar-dotnet-sdk-test/responses/results/ManageOfferResultTest.cs
- stellar-dotnet-sdk/responses/results/OfferEntry.cs
> Correctly parse OfferEntry when flag is unset

- stellar-dotnet-sdk-test/OperationTest.cs
- stellar-dotnet-sdk-test/xdr/TransactionDecodeTest.cs
- stellar-dotnet-sdk/Amount.cs
- stellar-dotnet-sdk/CreatePassiveOfferOperation.cs
- stellar-dotnet-sdk/CreatePassiveSellOfferOperation.cs
- stellar-dotnet-sdk/ManageBuyOfferOperation.cs
- stellar-dotnet-sdk/ManageOfferOperation.cs
- stellar-dotnet-sdk/ManageSellOfferOperation.cs
- stellar-dotnet-sdk/Price.cs
> Fix amount deserialization in non english cultures

- stellar-dotnet-sdk/stellar-dotnet-sdk.csproj
This was mentioned by @orbitlens on keybase
> Update NSec version dependency

- stellar-dotnet-sdk-test/WebAuthenticationTest.cs
- stellar-dotnet-sdk/InvalidWebAuthenticationException.cs
- stellar-dotnet-sdk/KeyPair.cs
- stellar-dotnet-sdk/WebAuthentication.cs
> Implement SEP 10: Stellar Web Authentication

- stellar-dotnet-sdk-test/ServerTest.cs
- stellar-dotnet-sdk-test/responses/LedgerDeserializeTest.cs
- stellar-dotnet-sdk-test/responses/SubmitTransactionResponseTest.cs
- stellar-dotnet-sdk/responses/LedgerResponse.cs
- stellar-dotnet-sdk/responses/OperationFeeStatsResponse.cs
- stellar-dotnet-sdk/responses/SubmitTransactionResponse.cs
- stellar-dotnet-sdk/responses/TransactionResponse.cs
> Changed longs of ledger sequence to uint32 (uint)

- docfx/docfx.json
- docfx/templates/docfx-stellar-template/src/partials/affix.tmpl.partial
- Removed button that could create new files via docs in github.
> DocFX Fix Git Contributions

- stellar-dotnet-sdk-test/requests/AccountsRequestBuilderTest.cs
- stellar-dotnet-sdk-test/stellar-dotnet-sdk-test.csproj
- stellar-dotnet-sdk-test/testdata/accountsWithSigner.json
- stellar-dotnet-sdk-test/testdata/accountsWithTrustline.json
- stellar-dotnet-sdk/requests/AccountsRequestBuilder.cs
I had a chat with @abuiles and we agreed not to validate the filtering on client side.
Fix #220
> Add accounts endpoint

- stellar-dotnet-sdk-test/requests/OffersRequestBuilderTest.cs
- stellar-dotnet-sdk/requests/OffersRequestBuilder.cs
Introduce the offers filter endpoints. Fix #221
> Add offers filter endpoint

- stellar-dotnet-sdk-test/requests/PathStrictReceiveRequestBuilderTest.cs
- stellar-dotnet-sdk-test/requests/PathStrictSendRequestBuilderTest.cs
- stellar-dotnet-sdk-test/stellar-dotnet-sdk-test.csproj
- stellar-dotnet-sdk/AssetExtensions.cs
- stellar-dotnet-sdk/Server.cs
- stellar-dotnet-sdk/requests/PathStrictReceiveRequestBuilder.cs
- stellar-dotnet-sdk/requests/PathStrictSendRequestBuilder.cs
Add the new endpoints `/path/strict-send` and `/path/strict-receive` with the same interface as the old `/paths` endpoint. Deprecate the old endpoint. Fix #222
> Add new paths endpoints

- stellar-dotnet-sdk/WebAuthentication.cs
Implement SEP-10 suggestion by @leighmcculloch
> Ensure VerifyTransactionSignatures does not return duplicate signers

- stellar-dotnet-sdk-test/TimeBoundsTest.cs
> Added UTC to the DateTime in the test of TimeBoundsTest

- stellar-dotnet-sdk-test/ServerCheckMemoRequiredTest.cs
- stellar-dotnet-sdk-test/ServerTest.cs
- stellar-dotnet-sdk/AccountRequiresMemoException.cs
- stellar-dotnet-sdk/Server.cs
- stellar-dotnet-sdk/SubmitTransactionOptions.cs
- stellar-dotnet-sdk/responses/AccountResponse.cs
Same as #241 , trying to fix coveralls being stuck.
Fixes #240
> Implement SEP0029

- stellar-dotnet-sdk-test/ServerCheckMemoRequiredTest.cs
- stellar-dotnet-sdk-test/responses/AccountDeserializerTest.cs
- stellar-dotnet-sdk-test/responses/EffectDeserializerTest.cs
- stellar-dotnet-sdk-test/stellar-dotnet-sdk-test.csproj
- stellar-dotnet-sdk-test/testdata/account.json
- stellar-dotnet-sdk-test/testdata/effectTrustlineAuthorizedToMaintainLiabilitiesEffect.json
- stellar-dotnet-sdk/responses/AccountResponse.cs
- stellar-dotnet-sdk/responses/Balance.cs
- stellar-dotnet-sdk/responses/EffectDeserializer.cs
- stellar-dotnet-sdk/responses/effects/TrustlineAuthorizedToMaintainLiabilitiesEffectResponse.cs
> Added Cap 18 Flags and isAuthorized flag

- stellar-dotnet-sdk-test/OperationTest.cs
- stellar-dotnet-sdk/AllowTrustOperation.cs
> Added AuthorizeToMaintainLiabilities and tests.

- stellar-dotnet-sdk-test/responses/TransactionDeserializerTest.cs
- stellar-dotnet-sdk-test/stellar-dotnet-sdk-test.csproj
- stellar-dotnet-sdk-test/testdata/transactionFeeBump.json
- stellar-dotnet-sdk/responses/TransactionResponse.cs
> Update horizon response protocol 13 #2

- stellar-dotnet-sdk-test/responses/TransactionDeserializerTest.cs
- stellar-dotnet-sdk/responses/TransactionResponse.cs
> Transaction pre protocol 13

- stellar-dotnet-sdk-test/responses/TransactionDeserializerTest.cs
- stellar-dotnet-sdk-test/stellar-dotnet-sdk-test.csproj
- stellar-dotnet-sdk-test/testdata/transactionTransactionWithMemo.json
- stellar-dotnet-sdk/responses/TransactionResponse.cs
> Added missing Memo Text from TransactionResponse.cs

- stellar-dotnet-sdk-test/requests/PathStrictReceiveRequestBuilderTest.cs
- stellar-dotnet-sdk-test/requests/PathStrictSendRequestBuilderTest.cs
- stellar-dotnet-sdk/requests/PathStrictReceiveRequestBuilder.cs
- stellar-dotnet-sdk/requests/PathStrictSendRequestBuilder.cs
> fix: change strict send/strict receive url paths

- stellar-dotnet-sdk-test/WebAuthenticationTest.cs
- stellar-dotnet-sdk/WebAuthentication.cs
> Update Web Authentication to reflect changes in SEP-10

- stellar-dotnet-sdk-test/responses/PredicateDeserializerTest.cs
- stellar-dotnet-sdk-test/testdata/effects/claimableBalance/claimableBalanceClaimantCreated.json
- stellar-dotnet-sdk/responses/Predicate.cs
> Change predicate json case to snake case

- stellar-dotnet-sdk-test/WebAuthenticationTest.cs
- stellar-dotnet-sdk/WebAuthentication.cs
> Sep 10 - 2.1

- stellar-dotnet-sdk-test/MemoTest.cs
- stellar-dotnet-sdk-test/responses/TransactionDeserializerTest.cs
- stellar-dotnet-sdk-test/stellar-dotnet-sdk-test.csproj
- stellar-dotnet-sdk-test/testdata/transactionTransactionTextMemo.json
- stellar-dotnet-sdk/Memo.cs
- stellar-dotnet-sdk/MemoText.cs
- stellar-dotnet-sdk/responses/TransactionResponse.cs
> Added Base64 conversion in case we have memo_bytes in the json to avoid length issues.

- stellar-dotnet-sdk-test/responses/results/BeginSponsoringFutureReservesResultTest.cs
- stellar-dotnet-sdk-test/responses/results/EndSponsoringFutureReservesResultTest.cs
- stellar-dotnet-sdk-test/responses/results/RevokeSponsorshipResultTest.cs
- stellar-dotnet-sdk/responses/results/BeginSponsoringFutureReservesAlreadySponsored.cs
- stellar-dotnet-sdk/responses/results/BeginSponsoringFutureReservesMalformed.cs
- stellar-dotnet-sdk/responses/results/BeginSponsoringFutureReservesRecursive.cs
- stellar-dotnet-sdk/responses/results/BeginSponsoringFutureReservesResult.cs
- stellar-dotnet-sdk/responses/results/BeginSponsoringFutureReservesSuccess.cs
- stellar-dotnet-sdk/responses/results/EndSponsoringFutureReservesNotSponsored.cs
- stellar-dotnet-sdk/responses/results/EndSponsoringFutureReservesResult.cs
- stellar-dotnet-sdk/responses/results/EndSponsoringFutureReservesSuccess.cs
- stellar-dotnet-sdk/responses/results/OperationResult.cs
- stellar-dotnet-sdk/responses/results/RevokeSponsorshipDoesNotExist.cs
- stellar-dotnet-sdk/responses/results/RevokeSponsorshipLowReserve.cs
- stellar-dotnet-sdk/responses/results/RevokeSponsorshipNotSponsor.cs
- stellar-dotnet-sdk/responses/results/RevokeSponsorshipOnlyTransferable.cs
- stellar-dotnet-sdk/responses/results/RevokeSponsorshipResult.cs
- stellar-dotnet-sdk/responses/results/RevokeSponsorshipSuccess.cs
> Added XDR missing results

- stellar-dotnet-sdk-test/ServerTest.cs
- stellar-dotnet-sdk/FeeBumpTransaction.cs
- stellar-dotnet-sdk/Server.cs
- stellar-dotnet-sdk/SubmitTransactionOptions.cs
- Added FeeBumpTransaction in SubmitTransactionOptions.
- Now SubmitTransaction checks if it's FeeBump or not.
- Added FromEnvelopeXdr in FeeBumpTransaction.
> Fix FeeBumpTransaction submit.

- stellar-dotnet-sdk-test/WebAuthenticationTest.cs
- stellar-dotnet-sdk/WebAuthentication.cs
> SEP-10 3.1 Changes

- README.md
Add missing instructions to README about how to reformat generated code.
I updated this part of the README in #304 and missed finishing the piece about formatting.
> Add missing instructions to README about how to reformat generated code

- stellar-dotnet-sdk-test/OperationTest.cs
- stellar-dotnet-sdk/ChangeTrustOperation.cs
> Added ChangeTrust no limit builder.

- stellar-dotnet-sdk-test/requests/OperationsRequestBuilderTest.cs
- stellar-dotnet-sdk-test/requests/TransactionsRequestBuilderTest.cs
- stellar-dotnet-sdk-test/responses/AssetPageDeserializerTest.cs
- stellar-dotnet-sdk-test/testdata/assetPage.json
- stellar-dotnet-sdk/requests/OperationsRequestBuilder.cs
- stellar-dotnet-sdk/requests/TransactionsRequestBuilder.cs
- stellar-dotnet-sdk/responses/AssetResponse.cs
> Updated Assets and Claimable Balances.

- stellar-dotnet-sdk-test/WebAuthenticationTest.cs
- stellar-dotnet-sdk/WebAuthentication.cs
> Sep 10 Client Domain feature.

- stellar-dotnet-sdk-test/responses/effects/LiquidityPoolRevokedEffectResponse/Data.json
- stellar-dotnet-sdk-test/responses/effects/LiquidityPoolRevokedEffectResponse/LiquidityPoolRevokedEffectResponseTest.cs
- stellar-dotnet-sdk/responses/effects/LiquidityPoolRevokedEffectResponse.cs
Fixes https://github.com/elucidsoft/dotnet-stellar-sdk/issues/343
> Now ReservesRevoked is an array in LiquidityPoolRevokedEffectResponse

- stellar-dotnet-sdk-xdr/stellar-dotnet-sdk-xdr.csproj
- stellar-dotnet-sdk/stellar-dotnet-sdk.csproj
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] My code follows the code style of this project.
> Added XML documentation to Nuget packages

- stellar-dotnet-sdk-test/FeeBumpTransactionTest.cs
- stellar-dotnet-sdk-test/MuxedAccountTest.cs
- stellar-dotnet-sdk-test/StrKeyTest.cs
- stellar-dotnet-sdk/MuxedAccountMed25519.cs
- stellar-dotnet-sdk/StrKey.cs
- stellar-dotnet-sdk/Util.cs
https://github.com/elucidsoft/dotnet-stellar-sdk/issues/364
> Fixes muxed account not working correctly.
